apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "quarkus/{{ .Values.app.name }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.service.targetPort }}
